# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-29 23:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='piblished_date',
            new_name='published_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='view',
            new_name='views',
        ),
    ]
